"""WO-83 — R41's two send-ready artifacts (G4.5; `BA_fleet_fuel.md` §2.4, R41,
R53).

R41's acceptance is the whole point of this file: *"Both artifacts for the same
(supplier, period) show identical lines and totals."* It is proven twice —
STRUCTURALLY (one loader, one column spec, two sync renderers that cannot query)
and CELL-FOR-CELL, by parsing the generated bytes with `openpyxl` and `pypdf`
and comparing both against the SAME hand-computed Decimal expectations.

Every euro here is hand-computed from the harvested formula, never read back
from the code under test:

    eur_l_doc = net_eur     / qty
    eur_l_eff = net_eur_eff / qty
    applied   = eur_l_doc − eur_l_eff
    short discount  when  applied < expected − 0.005
    recover_eur = gap × litres

Basis on every figure: **NET EUR/L, final — VAT excluded, rebates applied**
(§3.G G1 / R49). There is no float in this file's expectations and none in the
module it proves.
"""

from __future__ import annotations

import inspect
import io
import re
from datetime import date, timedelta
from decimal import Decimal

import pytest
from sqlalchemy import func, select

from app.core.errors import AppError
from app.models.audit import AuditEvent
from app.models.issuer import IssuerProfile
from app.models.transport.fuel_transaction import FuelTransaction
from app.services.transport import contract_audit, overcharge, overcharge_pack, supplier_entity
from tests.factories.transport import synthetic_iban, synthetic_vat_id, synthetic_vehicle_ref
from tests.transport.conftest import enable_transport, make_entity, make_org

pytestmark = pytest.mark.asyncio

PERIOD = "2026-05"
SUPPLIER = "Q8"
STATION = "Demo Station Riga"

# The one worked example, hand-computed: 1,000 L invoiced at EUR 1,350.00 with
# EUR 1,300.00 effective => applied 0.05 EUR/L against an agreed 0.20 EUR/L,
# gap 0.1500, recover 0.15 x 1000 = 150.00.
EXPECTED_ROW = [
    "2026-05-12",
    "LV",
    STATION,
    "Diesel",
    "1,000.000",
    "short discount",
    "0.2000",
    "0.0500",
    "0.1500",
    "150.00",
]
EXPECTED_TOTAL = Decimal("150.00")

# Generated, never literal: the factories keep every identifier fictional by
# construction (9-prefixed VAT bodies, test-only IBAN recipes) and keep
# `scripts/pii_scan.py` free of a hand-typed identifier to allowlist.
OUR_VAT = synthetic_vat_id("LV", seed=8301)
OUR_IBAN = synthetic_iban("LV", seed=8301)
SUPPLIER_VAT = synthetic_vat_id("LV", seed=8302)


# --------------------------------------------------------------------------- #
# Fixtures — the WO-82 detection-suite shapes, unchanged
# --------------------------------------------------------------------------- #


async def _txn(
    db_session,
    org_id: str,
    entity_id: str,
    *,
    line_seq: int,
    qty: Decimal = Decimal("1000.000"),
    net_eur: Decimal = Decimal("1350.00"),
    net_eur_eff: Decimal = Decimal("1300.00"),
    station: str = STATION,
    country: str = "LV",
    currency: str = "EUR",
    supplier: str = SUPPLIER,
) -> FuelTransaction:
    from app.services.transport import fuel_ingest

    vat_eur = (net_eur * Decimal("0.21")).quantize(Decimal("0.01"))
    return await fuel_ingest.ingest_transaction(
        db_session,
        org_id,
        entity_id=entity_id,
        supplier=supplier,
        period=PERIOD,
        line_seq=line_seq,
        country=country,
        vehicle_ref=synthetic_vehicle_ref(),
        txn_date=date(2026, 5, 12),
        station=station,
        product="DIESEL",
        qty=qty,
        currency=currency,
        net_local=net_eur,
        vat_local=vat_eur,
        gross_local=net_eur + vat_eur,
        net_eur=net_eur,
        vat_eur=vat_eur,
        # WO-88 (§4.15): a non-EUR line carries the FX provenance a real
        # ingestion records; EUR is the identity and needs none. Fixture
        # privilege raised — not one assertion below changes.
        fx_source=None if str(currency).upper() == "EUR" else "ecb",
        net_eur_eff=net_eur_eff,
    )


async def _letterhead(db_session, org_id: str) -> IssuerProfile:
    """A COMPLETE issuer company (`issuer.REQUIRED_FIELDS`, the Art. 226
    minimum) flagged default, so `_load_packet` resolves it as our letterhead.
    `make_entity` deliberately leaves `city`/`postal_code` blank, which is what
    the incomplete-letterhead refusal below exercises."""
    profile = IssuerProfile(
        org_id=org_id,
        name="Demo Haulage Group",
        legal_name="Demo Haulage Group SIA",
        is_default=True,
        vat_number=OUR_VAT,
        registration_number="REG-000999",
        address_line1="1 Synthetic Test Street",
        city="Testville",
        postal_code="LV-1000",
        country="LV",
        email="ap@demo-haulage.example",
        iban=OUR_IBAN,
    )
    db_session.add(profile)
    await db_session.flush()
    return profile


async def _org(db_session, *, with_letterhead: bool = True):
    org = await make_org(db_session, name="Overcharge Artifacts Org")
    await enable_transport(db_session, org.id)
    entity = await make_entity(db_session, org.id, country="LV", seed=831)
    if with_letterhead:
        await _letterhead(db_session, org.id)
    return org, entity


async def _claim(db_session, org_id: str, entity_id: str, **txn_kwargs):
    """One agreed term, one breaching line, one opened claim-back."""
    await contract_audit.set_term(
        db_session,
        org_id,
        supplier=SUPPLIER,
        country="LV",
        product_group="Diesel",
        expected_discount_eur_l=Decimal("0.20"),
    )
    await _txn(db_session, org_id, entity_id, line_seq=1, **txn_kwargs)
    return await overcharge.open_claim(db_session, org_id, supplier=SUPPLIER, period=PERIOD)


# --------------------------------------------------------------------------- #
# Parsing helpers — the generated BYTES are what is asserted
# --------------------------------------------------------------------------- #


def _workbook(data: bytes):
    from openpyxl import load_workbook

    return load_workbook(io.BytesIO(data))


def _fmt(kind: str, value) -> str:
    """The test's OWN formatter (never the module's): money 2 dp, rate 4 dp,
    litres 3 dp — the scales `contract_audit` quantized to."""
    dec = Decimal(str(value))
    if kind == "money":
        return f"{dec:,.2f}"
    if kind == "rate":
        return f"{dec:.4f}"
    return f"{dec:,.3f}"


_SHARED_KINDS = ("text", "text", "text", "text", "qty", "text", "rate", "rate", "rate", "money")


def _shared_rows(data: bytes) -> list[list[str]]:
    """The packet's shared demand block (the first 10 columns of `Evidence`),
    as display strings — the same values the letter prints."""
    ws = _workbook(data)[overcharge_pack.PACKET_SHEET_EVIDENCE]
    rows = list(ws.iter_rows(values_only=True))
    out: list[list[str]] = []
    for row in rows[1:]:
        if row[0] in (None, "", overcharge_pack.TOTAL_LABEL):
            break
        out.append(
            [
                str(row[i]) if _SHARED_KINDS[i] == "text" else _fmt(_SHARED_KINDS[i], row[i])
                for i in range(10)
            ]
        )
    return out


def _packet_total(data: bytes) -> Decimal:
    ws = _workbook(data)[overcharge_pack.PACKET_SHEET_EVIDENCE]
    for row in ws.iter_rows(values_only=True):
        if row[0] == overcharge_pack.TOTAL_LABEL:
            return Decimal(str(row[9]))
    raise AssertionError("the evidence sheet has no TOTAL row")


def _code_only(module) -> str:
    """A module's CODE with every docstring removed (AST round-trip) — so a
    structural scan asserts on what the module DOES, not on what its prose says
    it must never do."""
    import ast

    tree = ast.parse(inspect.getsource(module))
    for node in ast.walk(tree):
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                node.body = body[1:] or [ast.Pass()]
    return ast.unparse(tree)


def _pdf_text(data: bytes) -> str:
    from pypdf import PdfReader

    text = "".join(p.extract_text() or "" for p in PdfReader(io.BytesIO(data)).pages)
    return re.sub(r"\s+", " ", text)


def _assert_in_order(text: str, values: list[str]) -> None:
    """Every value appears, in this order — so the letter prints a ROW, not a
    coincidental scatter of matching substrings."""
    cursor = 0
    for value in values:
        idx = text.find(value, cursor)
        assert idx >= 0, f"{value!r} missing from the letter after position {cursor}"
        cursor = idx + len(value)


# --------------------------------------------------------------------------- #
# The Excel evidence packet
# --------------------------------------------------------------------------- #


async def test_wo83_the_evidence_packet_renders_every_line_cell_for_cell(db_session):
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)

    assert _shared_rows(data) == [EXPECTED_ROW]


async def test_wo83_the_evidence_packet_total_row_equals_the_hand_computed_sum(db_session):
    org, entity = await _org(db_session)
    await contract_audit.set_term(
        db_session,
        org.id,
        supplier=SUPPLIER,
        country="LV",
        product_group="Diesel",
        expected_discount_eur_l=Decimal("0.20"),
    )
    # Two breaching lines: 0.15 x 1000 = 150.00 and 0.10 x 2000 = 200.00.
    await _txn(db_session, org.id, entity.id, line_seq=1)
    await _txn(
        db_session,
        org.id,
        entity.id,
        line_seq=2,
        qty=Decimal("2000.000"),
        net_eur=Decimal("2600.00"),
        net_eur_eff=Decimal("2400.00"),
    )
    claim = await overcharge.open_claim(db_session, org.id, supplier=SUPPLIER, period=PERIOD)

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)

    rows = _shared_rows(data)
    assert [r[9] for r in rows] == ["150.00", "200.00"]
    assert _packet_total(data) == Decimal("350.00") == Decimal(str(claim.detected_eur))


async def test_wo83_the_packet_header_carries_the_claim_back_and_the_demand_dates(db_session):
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    header = {
        r[0]: r[1]
        for r in _workbook(data)[overcharge_pack.PACKET_SHEET_CLAIM].iter_rows(values_only=True)
    }

    assert header["Supplier"] == SUPPLIER
    assert header["Period"] == PERIOD
    assert header["Claim-back status"] == "detected"
    assert header["Currency"] == "EUR"
    assert Decimal(str(header["Recoverable total"])) == EXPECTED_TOTAL
    assert Decimal(str(header["Demanded (claim-back)"])) == EXPECTED_TOTAL
    letter_date = date.fromisoformat(header["Letter date"])
    assert date.fromisoformat(header["Payment due by"]) == letter_date + timedelta(days=30)


async def test_wo83_a_station_name_starting_with_a_formula_trigger_is_neutralised(db_session):
    """CWE-1236 through the ONE shared `core.csv_safety.sanitize_cell`: the
    free-text station is quote-prefixed, the money cell beside it is NOT (a
    leading `-` there is a negative amount, not an injection)."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id, station="=cmd|' /C calc'!A0")

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)

    ws = _workbook(data)[overcharge_pack.PACKET_SHEET_EVIDENCE]
    row = list(ws.iter_rows(values_only=True))[1]
    assert row[2] == "'=cmd|' /C calc'!A0"
    assert Decimal(str(row[9])) == EXPECTED_TOTAL


# --------------------------------------------------------------------------- #
# The formal PDF claim letter
# --------------------------------------------------------------------------- #


async def test_wo83_the_claim_letter_prints_the_same_lines_and_the_same_total(db_session):
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    text = _pdf_text(pdf)
    assert text.startswith("%") is False  # a real parse, not raw bytes
    _assert_in_order(text, EXPECTED_ROW)
    _assert_in_order(text, [overcharge_pack.TOTAL_LABEL, "150.00"])


async def test_wo83_both_artifacts_show_identical_lines_and_totals(db_session):
    """R41's acceptance, asserted across the PARSED BYTES of both artifacts."""
    org, entity = await _org(db_session)
    await contract_audit.set_term(
        db_session,
        org.id,
        supplier=SUPPLIER,
        country="LV",
        product_group="Diesel",
        expected_discount_eur_l=Decimal("0.20"),
    )
    await _txn(db_session, org.id, entity.id, line_seq=1)
    await _txn(
        db_session,
        org.id,
        entity.id,
        line_seq=2,
        qty=Decimal("2000.000"),
        net_eur=Decimal("2600.00"),
        net_eur_eff=Decimal("2400.00"),
        station="Demo Station Ventspils",
    )
    claim = await overcharge.open_claim(db_session, org.id, supplier=SUPPLIER, period=PERIOD)

    packet = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    letter = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    rows = _shared_rows(packet)
    assert len(rows) == 2
    text = _pdf_text(letter)
    for row in rows:
        _assert_in_order(text, row)
    assert _packet_total(packet) == Decimal("350.00")
    assert "350.00" in text


async def test_wo83_the_letter_carries_the_thirty_day_credit_or_refund_demand(db_session):
    """§2.4, verbatim: *"a formal PDF claim letter with a 30-day credit/refund
    demand"*. Both instruments are named and the due date is letter date + 30."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    text = _pdf_text(pdf)
    assert overcharge_pack.DEMAND_DAYS == 30
    assert "credit note or refund" in text
    assert "within 30 days" in text
    due = (date.today() + timedelta(days=30)).isoformat()
    assert due in text


async def test_wo83_both_artifacts_carry_the_r53_framing_and_the_price_basis(db_session):
    """R53: *"Each workbook carries its framing text."* The printed strings are
    the SAME constants the JSON API returns — no paraphrase can drift."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    packet = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    letter = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    wb = _workbook(packet)
    cells = {
        str(c)
        for sheet in (
            overcharge_pack.PACKET_SHEET_CLAIM,
            overcharge_pack.PACKET_SHEET_EVIDENCE,
        )
        for row in wb[sheet].iter_rows(values_only=True)
        for c in row
    }
    assert contract_audit.LEGAL_FRAMING in cells
    assert contract_audit.PRICE_BASIS in cells

    text = _pdf_text(letter)
    assert "Money the supplier owes" in contract_audit.LEGAL_FRAMING
    assert contract_audit.LEGAL_FRAMING in text
    assert contract_audit.PRICE_BASIS in text


async def test_wo83_the_letter_is_addressed_to_the_registered_per_country_entity(db_session):
    """R20/R21: the seller PRINTED on the invoice, resolved marker-only on the
    exact (supplier, country) key — never a fuzzy match."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await supplier_entity.set_registration(
        db_session,
        org.id,
        supplier=SUPPLIER,
        country="LV",
        vat_number=SUPPLIER_VAT,
        entity_name="Demo Fuel Card Latvia SIA",
    )

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    text = _pdf_text(pdf)
    assert "Demo Fuel Card Latvia SIA" in text
    assert SUPPLIER_VAT in text


async def test_wo83_an_unregistered_country_invents_no_entity_name(db_session):
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    text = _pdf_text(pdf)
    assert SUPPLIER in text
    assert "no registered legal entity on file" in text


async def test_wo83_the_letter_prints_our_letterhead_from_the_issuer_registry(db_session):
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    text = _pdf_text(pdf)
    assert "Demo Haulage Group SIA" in text
    assert OUR_VAT in text
    assert OUR_IBAN in text  # refunds go to our IBAN


# --------------------------------------------------------------------------- #
# The refusals — every one fails CLOSED
# --------------------------------------------------------------------------- #


async def test_wo83_a_claim_with_no_live_findings_refuses_no_overcharge_detected(db_session):
    """An empty document that reads as "we found nothing owed" is a different
    and false statement — so the pack refuses instead of emitting one."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await contract_audit.set_term(
        db_session,
        org.id,
        supplier=SUPPLIER,
        country="LV",
        product_group="Diesel",
        expected_discount_eur_l=Decimal("0.20"),
        active=False,
    )

    for build in (overcharge_pack.build_evidence_packet, overcharge_pack.build_claim_letter):
        with pytest.raises(AppError) as exc:
            await build(db_session, org.id, claim.id)
        assert exc.value.code == "no_overcharge_detected"
        assert exc.value.status == 422


async def test_wo83_a_drifted_detected_total_refuses_overcharge_evidence_drift(db_session):
    """§4.10 — the renderer recomputes and refuses a demand its own attached
    lines no longer reproduce (the `claim_pack.claim_totals_drift` twin)."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    claim.detected_eur = Decimal("900.00")
    await db_session.flush()

    for build in (overcharge_pack.build_evidence_packet, overcharge_pack.build_claim_letter):
        with pytest.raises(AppError) as exc:
            await build(db_session, org.id, claim.id)
        assert exc.value.code == "overcharge_evidence_drift"
        assert exc.value.status == 409
        assert "900.00" in exc.value.message and "150.00" in exc.value.message


async def test_wo83_a_terminal_claim_back_refuses_a_letter_but_still_yields_the_packet(db_session):
    """The packet is EVIDENCE and stays reproducible in every state (the WO-74
    precedent); the letter is a LIVE demand and must not assert an open debt the
    ledger records as closed."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await overcharge.advance_claim(db_session, org.id, claim.id, to_status="packaged")
    await overcharge.advance_claim(db_session, org.id, claim.id, to_status="claimed")
    await overcharge.advance_claim(db_session, org.id, claim.id, to_status="rejected")

    with pytest.raises(AppError) as exc:
        await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)
    assert exc.value.code == "overcharge_claim_closed"
    assert exc.value.status == 409

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    assert _packet_total(data) == EXPECTED_TOTAL


async def test_wo83_a_packaged_claim_back_still_yields_a_letter(db_session):
    """`packaged` and `claimed` are the states a demand is actually sent in —
    only the three TERMINAL states refuse."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await overcharge.advance_claim(db_session, org.id, claim.id, to_status="packaged")

    pdf = await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)
    assert pdf[:4] == b"%PDF"


async def test_wo83_an_incomplete_letterhead_refuses_the_letter_naming_the_fields(db_session):
    """A formal demand from an unnamed, unaddressed party is not a formal
    demand — `issuer.REQUIRED_FIELDS` is the Art. 226 minimum. The PACKET is an
    attachment and needs no letterhead, so it still renders."""
    org, entity = await _org(db_session, with_letterhead=False)
    claim = await _claim(db_session, org.id, entity.id)

    with pytest.raises(AppError) as exc:
        await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)
    assert exc.value.code == "issuer_profile_incomplete"
    assert exc.value.status == 409
    assert "city" in exc.value.message and "postal_code" in exc.value.message

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    assert _packet_total(data) == EXPECTED_TOTAL


async def test_wo83_the_module_gate_fails_closed(db_session):
    from app.services import modules

    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await modules.set_enabled(db_session, org.id, "transport", False)

    for build in (overcharge_pack.build_evidence_packet, overcharge_pack.build_claim_letter):
        with pytest.raises(AppError) as exc:
            await build(db_session, org.id, claim.id)
        assert exc.value.code == "module_not_enabled"
        assert exc.value.status == 403


async def test_wo83_a_cross_tenant_claim_id_is_an_opaque_404(db_session):
    """§4.4 — object-id guessing must yield zero information."""
    org_a, entity_a = await _org(db_session)
    claim_a = await _claim(db_session, org_a.id, entity_a.id)

    org_b = await make_org(db_session, name="Other Overcharge Org")
    await enable_transport(db_session, org_b.id)

    for build in (overcharge_pack.build_evidence_packet, overcharge_pack.build_claim_letter):
        with pytest.raises(AppError) as exc:
            await build(db_session, org_b.id, claim_a.id)
        assert exc.value.code == "overcharge_claim_not_found"
        assert exc.value.status == 404


async def test_wo83_an_issuer_from_another_org_is_an_opaque_404(db_session):
    org_a, entity_a = await _org(db_session)
    claim = await _claim(db_session, org_a.id, entity_a.id)
    org_b = await make_org(db_session, name="Foreign Letterhead Org")
    foreign = await _letterhead(db_session, org_b.id)

    with pytest.raises(AppError) as exc:
        await overcharge_pack.build_claim_letter(
            db_session, org_a.id, claim.id, issuer_id=foreign.id
        )
    assert exc.value.code == "issuer_not_found"
    assert exc.value.status == 404


# --------------------------------------------------------------------------- #
# The structural guarantees — R41's one-source rule, §4.14, §4.19
# --------------------------------------------------------------------------- #


async def test_wo83_both_renderers_consume_the_one_shared_row_builder():
    """Identity is STRUCTURAL: both renderers project from `_evidence_rows`
    over the same `_COLUMNS` spec, and neither reads `packet.lines` itself."""
    for fn in (overcharge_pack._render_evidence_workbook, overcharge_pack._render_claim_letter):
        src = inspect.getsource(fn)
        assert "_evidence_rows(" in src, f"{fn.__name__} bypasses the one table builder"
        assert "_total_row(" in src, f"{fn.__name__} builds its own total"
        assert "packet.lines" not in src.replace("len(packet.lines)", ""), (
            f"{fn.__name__} reads the lines directly instead of the shared builder"
        )


async def test_wo83_the_renderers_cannot_query_the_database():
    """Both renderers are SYNC functions over a loaded packet — no session, no
    second source, so "identical lines" cannot be broken by a stray query."""
    for fn in (overcharge_pack._render_evidence_workbook, overcharge_pack._render_claim_letter):
        assert not inspect.iscoroutinefunction(fn)
        assert list(inspect.signature(fn).parameters) == ["packet"]


async def test_wo83_the_one_line_source_is_contract_audit_audit():
    """R41's "built from the SAME line source": `_load_packet` calls
    `contract_audit.audit` — the same call `overcharge.open_claim` snapshots —
    and no other query produces a figure."""
    src = inspect.getsource(overcharge_pack._load_packet)
    assert "contract_audit.audit(" in src
    assert "select(" not in src, "the loader forked a query of its own"


async def test_wo83_the_module_is_float_free_and_reads_no_document_currency_column():
    """§4.9 / §4.14 — Decimal only, EUR only. The three document-currency amount
    columns are never read; a line's currency rides the packet as PROVENANCE."""
    # Docstrings are stripped first: this module's prose legitimately QUOTES
    # the things the code must not do ("No float anywhere", "never
    # `issuer.get_or_create`"), and a scan that trips on its own documentation
    # would push a future author to delete the reasoning instead of the defect.
    src = _code_only(overcharge_pack)
    assert "float" not in src
    for col in ("net_local", "vat_local", "gross_local"):
        assert col not in src, f"{col} read in a EUR-only artifact (§4.14)"
    assert "get_or_create" not in src, "a read-only artifact must not create an issuer row"


async def test_wo83_mixed_currency_lines_total_in_eur_and_never_sum_a_local_amount(db_session):
    """§4.14 — a supplier month spanning EUR and PLN produces ONE EUR total
    equal to the hand-computed Decimal sum; the PLN line's own currency is
    printed as provenance and never totalled."""
    org, entity = await _org(db_session)
    await contract_audit.set_term(
        db_session,
        org.id,
        supplier=SUPPLIER,
        country="LV",
        product_group="Diesel",
        expected_discount_eur_l=Decimal("0.20"),
    )
    await _txn(db_session, org.id, entity.id, line_seq=1)  # EUR -> 150.00
    await _txn(
        db_session,
        org.id,
        entity.id,
        line_seq=2,
        currency="PLN",
        qty=Decimal("2000.000"),
        net_eur=Decimal("2600.00"),
        net_eur_eff=Decimal("2400.00"),
    )  # -> 200.00
    claim = await overcharge.open_claim(db_session, org.id, supplier=SUPPLIER, period=PERIOD)

    data = await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)

    assert _packet_total(data) == Decimal("350.00")
    ws = _workbook(data)[overcharge_pack.PACKET_SHEET_EVIDENCE]
    rows = list(ws.iter_rows(values_only=True))
    currencies = [rows[1][13], rows[2][13]]
    assert sorted(currencies) == ["EUR", "PLN"]
    header = {
        r[0]: r[1]
        for r in _workbook(data)[overcharge_pack.PACKET_SHEET_CLAIM].iter_rows(values_only=True)
    }
    assert header["Currency"] == "EUR"


async def test_wo83_generating_both_artifacts_mutates_nothing_and_audits_nothing(db_session):
    """R41 "read-only over the analytics" / §4.19: after building BOTH
    artifacts the claim-back and every fuel-transaction column are identical and
    no audit row was written."""
    org, entity = await _org(db_session)
    claim = await _claim(db_session, org.id, entity.id)
    await db_session.commit()

    def snapshot(obj, columns):
        return {c: getattr(obj, c) for c in columns}

    claim_cols = (
        "supplier",
        "period",
        "status",
        "detected_eur",
        "recovered_eur",
        "lines_count",
        "note",
    )
    txn_cols = tuple(c.name for c in FuelTransaction.__table__.columns)

    before_claim = snapshot(claim, claim_cols)
    before_txns = [
        snapshot(t, txn_cols)
        for t in await db_session.scalars(
            select(FuelTransaction).where(FuelTransaction.org_id == org.id)
        )
    ]
    before_audit = await db_session.scalar(
        select(func.count()).select_from(AuditEvent).where(AuditEvent.org_id == org.id)
    )

    await overcharge_pack.build_evidence_packet(db_session, org.id, claim.id)
    await overcharge_pack.build_claim_letter(db_session, org.id, claim.id)

    await db_session.refresh(claim)
    assert snapshot(claim, claim_cols) == before_claim
    after_txns = [
        snapshot(t, txn_cols)
        for t in await db_session.scalars(
            select(FuelTransaction).where(FuelTransaction.org_id == org.id)
        )
    ]
    assert after_txns == before_txns
    after_audit = await db_session.scalar(
        select(func.count()).select_from(AuditEvent).where(AuditEvent.org_id == org.id)
    )
    assert after_audit == before_audit
