"""partner workflow and penalty invoices

Revision ID: 18312e6f00a5
Revises: 1fec6fa2d082
Create Date: 2026-07-20 12:42:50.302309
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = '18312e6f00a5'
down_revision: Union[str, None] = '1fec6fa2d082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('requires_contract', sa.Boolean(), nullable=False),
    sa.Column('requires_acceptance', sa.Boolean(), nullable=False),
    sa.Column('penalty_enabled', sa.Boolean(), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_partners_org_name', ['org_id', 'name'], unique=False)

    op.create_table('partner_documents',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('partner_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('signed_by', sa.String(length=200), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_documents', schema=None) as batch_op:
        batch_op.create_index('ix_partner_docs_partner', ['partner_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_documents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_documents_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', app.models.base.GUID(), nullable=True))
        # server_default backfills existing rows as normal (non-penalty) invoices.
        batch_op.add_column(sa.Column('kind', sa.String(length=12), nullable=False, server_default='standard'))
        batch_op.create_index(batch_op.f('ix_issued_invoices_partner_id'), ['partner_id'], unique=False)
        batch_op.create_foreign_key('fk_issued_partner', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_issued_partner', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_issued_invoices_partner_id'))
        batch_op.drop_column('kind')
        batch_op.drop_column('partner_id')

    with op.batch_alter_table('partner_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_documents_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_documents_org_id'))
        batch_op.drop_index('ix_partner_docs_partner')

    op.drop_table('partner_documents')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('ix_partners_org_name')
        batch_op.drop_index(batch_op.f('ix_partners_org_id'))

    op.drop_table('partners')
    # ### end Alembic commands ###
