"""issued invoice delivery penalty and email outbox

Revision ID: 1fec6fa2d082
Revises: 944f91c9fe76
Create Date: 2026-07-20 12:22:41.252036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = '1fec6fa2d082'
down_revision: Union[str, None] = '944f91c9fe76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_email_org_created', ['org_id', 'created_at'], unique=False)

    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('penalty_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reminder_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_reminder_at', sa.Date(), nullable=True))

    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_penalty_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.drop_column('default_penalty_rate')

    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_at')
        batch_op.drop_column('reminder_count')
        batch_op.drop_column('penalty_rate')
        batch_op.drop_column('buyer_email')

    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_email_org_created')
        batch_op.drop_index(batch_op.f('ix_email_messages_org_id'))

    op.drop_table('email_messages')
    # ### end Alembic commands ###
