"""expense approvers and bank verification

Revision ID: 2b340c7660c5
Revises: 18312e6f00a5
Create Date: 2026-07-20 13:48:33.135485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = '2b340c7660c5'
down_revision: Union[str, None] = '18312e6f00a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_reference', sa.String(length=300), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_expense_approver', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    # Preserve existing behaviour: everyone who could approve before (admins and
    # sysadmins) stays an approver. Owners/admins can refine the list afterwards.
    op.execute(
        "UPDATE users SET is_expense_approver = 1 WHERE role IN ('admin', 'sysadmin')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_expense_approver')

    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.drop_column('bank_reference')

    # ### end Alembic commands ###
