"""issued invoice payment tracking

Revision ID: 944f91c9fe76
Revises: ac991e5874b0
Create Date: 2026-07-20 11:54:15.547126
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = '944f91c9fe76'
down_revision: Union[str, None] = 'ac991e5874b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        # server_default backfills any pre-existing rows with 0; the ORM supplies
        # the value going forward so the DB-side default is only a migration aid.
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=14, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('paid_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.drop_column('paid_date')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
