"""audit events

Revision ID: ac991e5874b0
Revises: ec6b16191e19
Create Date: 2026-07-20 11:03:55.450910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = 'ac991e5874b0'
down_revision: Union[str, None] = 'ec6b16191e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('at_ms', sa.BigInteger(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'seq', name='uq_audit_org_seq')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_audit_org_action', ['org_id', 'action'], unique=False)
        batch_op.create_index('ix_audit_org_seq', ['org_id', 'seq'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_seq')
        batch_op.drop_index('ix_audit_org_action')
        batch_op.drop_index(batch_op.f('ix_audit_events_org_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
