"""initial schema

Revision ID: ec6b16191e19
Revises: 
Create Date: 2026-07-20 10:19:03.607466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # portable GUID type used by every table


revision: str = 'ec6b16191e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecb_rates',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'currency', name='uq_ecb_rate_date_ccy')
    )
    with op.batch_alter_table('ecb_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecb_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecb_rates_rate_date'), ['rate_date'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ai_validation_enabled', sa.Boolean(), nullable=False),
    sa.Column('human_validation_enabled', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_policies',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('monthly_invoice_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_upload_limit', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', name='uq_role_policy_role')
    )
    op.create_table('budget_targets',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'category', name='uq_budget_org_category')
    )
    with op.batch_alter_table('budget_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_targets_org_id'), ['org_id'], unique=False)

    op.create_table('email_intakes',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_email_intake_org')
    )
    with op.batch_alter_table('email_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_intakes_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_intakes_token'), ['token'], unique=True)

    op.create_table('invitations',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user_free', 'user', 'admin', 'sysadmin', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.String(length=200), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('issued_invoices',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('supply_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_vat_number', sa.String(length=32), nullable=True),
    sa.Column('buyer_address_line1', sa.String(length=200), nullable=True),
    sa.Column('buyer_city', sa.String(length=120), nullable=True),
    sa.Column('buyer_postal_code', sa.String(length=20), nullable=True),
    sa.Column('buyer_country', sa.String(length=2), nullable=True),
    sa.Column('seller_json', sa.Text(), nullable=False),
    sa.Column('vat_scheme', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issued_invoices_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_issued_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_issued_org_issue', ['org_id', 'issue_date'], unique=False)

    op.create_table('issuer_profiles',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=16), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('logo_mime', sa.String(length=40), nullable=True),
    sa.Column('logo_data', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuer_profiles_org_id'), ['org_id'], unique=True)

    op.create_table('org_modules',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_org_module')
    )
    with op.batch_alter_table('org_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_modules_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user_free', 'user', 'admin', 'sysadmin', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('vendors',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_vendor_org_name')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('ix_vendors_org_country', ['org_id', 'country'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_org_id'), ['org_id'], unique=False)

    op.create_table('expense_reports',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('employee_id', app.models.base.GUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_reports_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_reports_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_reports_status'), ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('vendor_id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'paid', 'overdue', name='invoice_status'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fx_source', sa.String(length=16), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_findings', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index('ix_invoices_org_currency', ['org_id', 'currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_invoices_org_issue', ['org_id', 'issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_validation_status'), ['validation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('issued_invoice_lines',
    sa.Column('invoice_id', app.models.base.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['issued_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issued_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issued_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('expense_comments',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('report_id', app.models.base.GUID(), nullable=False),
    sa.Column('author_id', app.models.base.GUID(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_comments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_comments_report_id'), ['report_id'], unique=False)

    op.create_table('expense_items',
    sa.Column('report_id', app.models.base.GUID(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('receipt_mime', sa.String(length=60), nullable=True),
    sa.Column('receipt_data', sa.LargeBinary(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_items_report_id'), ['report_id'], unique=False)

    op.create_table('inbound_invoices',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('from_addr', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('draft_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('invoice_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_invoices_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_invoices_status'), ['status'], unique=False)

    op.create_table('line_items',
    sa.Column('invoice_id', app.models.base.GUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_items_category'), ['category'], unique=False)
        batch_op.create_index('ix_line_items_invoice_category', ['invoice_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('expense_transactions',
    sa.Column('org_id', app.models.base.GUID(), nullable=False),
    sa.Column('employee_id', app.models.base.GUID(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('item_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['expense_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_exp_txn_employee_status', ['employee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_transactions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_transactions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_transactions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_expense_transactions_org_id'))
        batch_op.drop_index(batch_op.f('ix_expense_transactions_employee_id'))
        batch_op.drop_index('ix_exp_txn_employee_status')

    op.drop_table('expense_transactions')
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_items_invoice_id'))
        batch_op.drop_index('ix_line_items_invoice_category')
        batch_op.drop_index(batch_op.f('ix_line_items_category'))

    op.drop_table('line_items')
    with op.batch_alter_table('inbound_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_inbound_invoices_sha256'))
        batch_op.drop_index(batch_op.f('ix_inbound_invoices_org_id'))

    op.drop_table('inbound_invoices')
    with op.batch_alter_table('expense_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_items_report_id'))

    op.drop_table('expense_items')
    with op.batch_alter_table('expense_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_comments_report_id'))
        batch_op.drop_index(batch_op.f('ix_expense_comments_org_id'))

    op.drop_table('expense_comments')
    with op.batch_alter_table('issued_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issued_invoice_lines_invoice_id'))

    op.drop_table('issued_invoice_lines')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_validation_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index('ix_invoices_org_issue')
        batch_op.drop_index(batch_op.f('ix_invoices_org_id'))
        batch_op.drop_index('ix_invoices_org_currency')
        batch_op.drop_index(batch_op.f('ix_invoices_issue_date'))

    op.drop_table('invoices')
    with op.batch_alter_table('expense_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_reports_status'))
        batch_op.drop_index(batch_op.f('ix_expense_reports_org_id'))
        batch_op.drop_index(batch_op.f('ix_expense_reports_employee_id'))

    op.drop_table('expense_reports')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_org_id'))
        batch_op.drop_index('ix_vendors_org_country')

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('org_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_modules_org_id'))

    op.drop_table('org_modules')
    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuer_profiles_org_id'))

    op.drop_table('issuer_profiles')
    with op.batch_alter_table('issued_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_issued_org_issue')
        batch_op.drop_index(batch_op.f('ix_issued_invoices_org_id'))
        batch_op.drop_index(batch_op.f('ix_issued_invoices_number'))

    op.drop_table('issued_invoices')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_org_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('email_intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_intakes_token'))
        batch_op.drop_index(batch_op.f('ix_email_intakes_org_id'))

    op.drop_table('email_intakes')
    with op.batch_alter_table('budget_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_targets_org_id'))

    op.drop_table('budget_targets')
    op.drop_table('role_policies')
    op.drop_table('organizations')
    with op.batch_alter_table('ecb_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecb_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_ecb_rates_currency'))

    op.drop_table('ecb_rates')
    # ### end Alembic commands ###
